FROM mxnet/python:1.4.1_gpu_cu100_py3

LABEL SongChao chaosong@bjtu.edu.cn

RUN apt-get update && apt-get install graphviz -y

RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple pytest graphviz==0.8.4